---
title: "kmeans"
author: "sunny"
date: "`r Sys.Date()`"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages("plot3D")
install.packages("rgl")

```


```{r}
#install.packages("scatterplot3d") # Install
library("scatterplot3d")
```

```{r}
library(tidyverse)  
library(cluster)    
library(factoextra)
library(ggplot2)
#library("plot3D")
#library(rgl)
library(magick)
```


```{r}
data<-iris
summary(data)
```
```{r}
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species)) + 
    geom_point(size=3)
    
```
```{r}
colors <- c("red", "blue", "orange")
colors <- colors[as.numeric(iris$Species)]
scatterplot3d(iris[,1:3], pch = 16, color=colors)
```


```{r}
data = data[1:4]
data
```
```{r}
data_scaled <- scale(data)
head(data_scaled,5)
```
```{r}
summary(data_scaled)
```

```{r}
distance <- get_dist(data_scaled)
```
```{r}
fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
```

```{r}
k2 <- kmeans(data_scaled , centers = 2, nstart = 25)
str(k2)
```
```{r}
class(k2$cluster)
```

```{r}

#data_scaled['cluster'] = [k2$cluster]
#View(data_scaled)
```

```{r}
fviz_cluster(k2, data = data_scaled)
```

```{r}
k3 <- kmeans(data_scaled , centers = 3, nstart = 25)
fviz_cluster(k3, data = data_scaled)
```

```{r}
k4 <- kmeans(data_scaled , centers = 4, nstart = 25)
fviz_cluster(k4, data = data_scaled)
```
```{r}
k5 <- kmeans(data_scaled , centers = 5, nstart = 25)
fviz_cluster(k5, data = data_scaled)
```


```{r}
set.seed(123)

fviz_nbclust(data_scaled, kmeans, method = "wss")
```

```{r}

```


---------------------------------------------------------------------
    US arrest data
    
```{r}
df_crime <- USArrests
summary(df_crime)
```
```{r}
df_crime<- na.omit(df_crime)
```

```{r}
df_crime <- scale(df_crime)
head(df_crime )
```
```{r}
distance <- get_dist(df_crime)
fviz_dist(distance)
```
```{r}
k2 <- kmeans(df_crime, centers = 2, nstart = 25)
str(k2)
```
```{r}
k2
```
```{r}
fviz_cluster(k2, data = df_crime)
```
```{r}
df_crime %>%
  as_tibble() %>%
  mutate(cluster = k2$cluster,
         state = row.names(USArrests)) %>%
  ggplot(aes(Assault, Murder, color = factor(cluster), label = state)) +
  geom_text()
```
```{r}
set.seed(123)

fviz_nbclust(df_crime, kmeans, method = "wss")
```



------------------------------------------------------------------
         PROTEIN DATA
         
```{r}
protein <- read.csv("/Users/sunny/Documents/sunny/projects/machine learning/R/week5/Lab05_R/protein.csv")
summary(protein)
```
```{r}
dist_protein <- dist(protein[,-1], method = 'euclidian')
```

```{r}
hc_protein <- hclust(dist_protein, method = 'complete')
hc_protein

# plot the associated dendrogram
plot(hc_protein, hang = -0.1, labels = protein$Country)
```

```{r}


